version: "3"
services:
  db:
    image: postgres
    environment:
      RAILS_ENV: development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    volumes:
      - "redis:/data"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails dev:cache && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

volumes:
  redis:
