default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webcrawler_development
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: webcrawler_test
  host: db
  username: postgres

production:
  <<: *default
  database: webcrawler_production
  username: webcrawler
  password: <%= ENV['WEBCRAWLER_DATABASE_PASSWORD'] %>
